project_id = "rwinelghzsuetpgrzwph"

[functions.get-mapbox-token]
verify_jwt = false

[functions.update-material-rankings]
verify_jwt = true

[functions.scrape-product-image]
verify_jwt = false

[functions.populate-materials]
verify_jwt = false

[functions.deep-crawl-products]
verify_jwt = false

[functions.populate-catalog-products]
verify_jwt = false

[functions.enrich-products]
verify_jwt = false

[functions.import-spreadsheet-materials]
verify_jwt = false

[functions.bulk-import-products]
verify_jwt = false
